### PR TITLE
Rename model names

### PR DESCRIPTION
**Pull request by hirao-k**
- Building -> BlueprintAnalysisBuilding
- BuildingSite -> BlueprintAnalysisBuildingSite
- Blueprint -> BlueprintBuilding

To avoid confusion, use same name of database. ( To avoid conflict somewhere, Blueprint was not renamed to Building, but BlueprintBuilding ) 

building repository PR https://github.com/thanhtetaung/building/pull/5 

https://app.diagrams.net/#G1cGCFOgGSsL9aKeHzNZWc9_DKMpkTqy99 
Landing Page UML, Flow-UML v2

### CODE REVIEW

**Comment by thanhtetaung** [comment]
@hirao-k Please see my comment on [Backend PR](https://github.com/thanhtetaung/building-web/pull/33). Frontend code also need to refactor later. 

Current BluePrint is representing Building information. So later need to change to Building. 

BuildingSite should keep using.

Current Building class may drop in future.

And frontend site always won't need to be same with backend structure and name. As my experience, in most of the cases they are different structure for simplicity (especially when we use RDBMS in backend).

**Comment by hirao-k** [comment]
@thanhtetaung  All right, but I intend to assign frontend issues to y-lin.  After you change structure, please tell us  it.

**Comment by thanhtetaung** [comment]
> @thanhtetaung All right, but I intend to assign frontend issues to y-lin. After you change structure, please tell us it.

@hirao-k I think frontend issues is just to change UI right? If so, needless to wait for structure change (Because I'm planning to refactor when new features are added. I saw that Company and Project features are being added). Or I can give some time to change this issue tomorrow if you can wait.

**Comment by hirao-k** [comment]
@thanhtetaung 

> I think frontend issues is just to change UI right? 

Yes, I decided so https://komugi-lab.slack.com/archives/C015DS32012/p1625540880090200?thread_ts=1625539565.088500&cid=C015DS32012 

> I can give some time to change this issue tomorrow if you can wait.

Thank you.  I can wait more days.
I assigned new issue https://github.com/thanhtetaung/building-web/issues/34 shared fixed version of data structure. 
Please refer it, and I entrust you details ( you can implement as you think better ).

**Pull request closed without merging**
